[package]
name = "xore"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
clap = {version = "4.5.28", features = ["derive"]}
zstd = "0.13.2"
indicatif = "0.17.11"
base64 = "0.22.1"
